# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Lover' do
    pod 'AFNetworking', '~> 3.1.0'
    pod 'MJRefresh'
    pod 'SDWebImage', '~> 3.8.0'
    pod 'MBProgressHUD', '~> 1.0.0'

end
